#设置数据源
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flower-sing?useUnicode=true&characterEncoding=utf-8
    username: demo
    password: demo
    max-active: 100
    test-while-idle: false
    test-on-borrow: true
    validation-query: select 1
    remove-abandoned: true
    remove-abandoned-timeout: 300
    log-abandoned: true
    initialize: false
